apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
# Resource names in a shared namespace must be unique
#
namePrefix: qcon-guide-
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.6.11-e9ac1458--2023-09-27.1695773908 # {"$imagepolicy": "qcon:qcon-guide-image-policy:tag"}
images:
  - name: "qcon-guide"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-guide"
    newTag: "1.6.11-e9ac1458--2023-09-27.1695773908" # {"$imagepolicy": "qcon:qcon-guide-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
# Updates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-guide-latest
    behavior: merge
