apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.6.6-4969b770--2023-06-28.1687922442 # {"$imagepolicy": "qcon:qcon-guide-image-policy:tag"}
images:
  - name: "qcon-guide"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-guide"
    newTag: "1.6.6-4969b770--2023-06-28.1687922442" # {"$imagepolicy": "qcon:qcon-guide-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-guide-latest
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
