version: "3"

services:
  app:
    image: infrastructure-documentation
    build:
      target: build
    environment:
      - DEBUG=true
      - CI=false
    volumes:
    - ./:/docs
    ports:
      - 8000:8000
