# fly.toml app configuration file generated for qcon-guide on 2024-07-17T14:37:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qcon-guide'
primary_region = 'yyz'

[build]

[env]
  TS_HOSTNAME = 'qcon-guide'

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = false
  force_https = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256Mb'
  cpu_kind = 'shared'
  cpus = 1
