site_name: Qcon Guide
site_url: https://qcon-guide.ltc.bcit.ca

repo_name: qcon-guide
repo_url: https://issues.ltc.bcit.ca/web-apps/qcon/qcon-user-guide

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: teal
    accent: green
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: 'Work Sans'
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top

extra_css:
  - css/qcon-guide.css

plugins:
  - search

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - index.md
<<<<<<< Updated upstream
  - 'Simple Conversion': 'simple-conversion.md'
  - 'Uploading to Learning Hub': 'import-to-lh.md'
  - 'Question Type':
      - 'Multiple Choice (MC)': 'question-type/multiple-choice.md'
      - 'True/False (TF)': 'question-type/true-false.md'
      - 'Multiple-Select (MS)': 'question-type/multiple-select.md'
      - 'Fill-in the Blanks (FIB)': 'question-type/fill-in-the-blanks.md'
      - 'Matching (MAT)': 'question-type/matching.md'
      - 'Ordering (ORD)': 'question-type/ordering.md'
      - 'Written Response (WR)': 'question-type/written-response.md'
  - 'Info':
    - 'Using Answer Key at the end of the Document': 'info/end-answer-key.md' 
    - 'Randomizing the Answers': 'info/answers-randomization.md'
    - 'Ordered List': 'info/ordered-list.md'
    - 'Respondus Comparison': 'info/respondus-comparison.md'
=======
  - basic-question-types.md
  - media-links.md
  - qcon-process.md
  - Question Type Details:
      - 'True/False (TF)': 'detailed-question-types/true-false.md'
      - 'Multiple Choice (MC)': 'detailed-question-types/multiple-choice.md'
      - 'Multiple-Select (MS)': 'detailed-question-types/multiple-select.md'
      - 'Written Response (WR)': 'detailed-question-types/written-response.md'
      - 'Fill-in-Blank (FIB)': 'detailed-question-types/fill-in-blanks.md'
      - 'Matching (MAT)': 'detailed-question-types/matching.md'
      - 'Ordering (ORD)': 'detailed-question-types/ordering.md'
  -  Additional Information:
      - additional-info/sections.md
      - 'Using an Answer Key': 'additional-info/end-answer-key.md' 
      - 'Randomizing Answers': 'additional-info/answer-randomization.md'
      - additional-info/migrating-from-respondus.md
>>>>>>> Stashed changes
