site_name: Qcon User Guide
site_url: https://qcon-user-guide.dev.ltc.bcit.ca

# Set to false for local docs development
strict: false

theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: green
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: 'Work Sans'
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top

plugins:
  - search

markdown_extensions:
  - meta
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.details
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materdialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - index.md
  - inline-answers.md
  - 'Question Type':
      - 'Multiple Choice': 'question-type/multiple-choice.md'
  - end-answers.md
  - respondus-comparison.md
