site_name: Qcon User Guide
site_url: https://qcon-user-guide.dev.ltc.bcit.ca

# Set to false for local docs development
strict: false

theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: green
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: 'Work Sans'
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top

extra_css:
  - css/qcon-guide.css

plugins:
  - search

markdown_extensions:
  - meta
  - abbr
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.details
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materdialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - index.md
  - 'Simple Conversion': 'simple-conversion.md'
  - 'Uploading to Learning Hub': 'import-to-lh.md'
  - 'Question Type':
      - 'Multiple Choice (MC)': 'question-type/multiple-choice.md'
      - 'True/False (TF)': 'question-type/true-false.md'
      - 'Multiple-Select (MS)': 'question-type/multiple-select.md'
      - 'Fill-in the Blanks (FIB)': 'question-type/fill-in-the-blanks.md'
      - 'Matching (MAT)': 'question-type/matching.md'
      - 'Ordering (ORD)': 'question-type/ordering.md'
      - 'Written Response (WR)': 'question-type/written-response.md'
  - 'Info':
    - 'Using Answer Key at the end of the Document': 'info/end-answer-key.md' 
    - 'Randomizing the Answers': 'info/answers-randomization.md'
    - 'Respondus Comparison': 'info/respondus-comparison.md'
