site_name: Qcon Guide
site_url: https://qcon-guide.ltc.bcit.ca

repo_name: qcon.ltc.bcit.ca   # Hijack icon to point to qcon service
repo_url: https://qcon.ltc.bcit.ca

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: teal
    accent: green
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: 'Work Sans'
  features:
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.footer
    - content.code.annotate
  icon:
    repo: fontawesome/solid/link

extra:
  social:
    - icon: fontawesome/solid/envelope 
      link: mailto:courseproduction@bcit.ca

extra_css:
  - css/qcon-guide.css

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

markdown_extensions:
  - abbr
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: true
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - index.md
  - qcon-process.md
  - basic-question-types.md
  - Question Type Details:
      - 'True/False (TF)': 'detailed-question-types/true-false.md'
      - 'Multiple Choice (MC)': 'detailed-question-types/multiple-choice.md'
      - 'Multiple-Select (MS)': 'detailed-question-types/multiple-select.md'
      - 'Written Response (WR)': 'detailed-question-types/written-response.md'
      - 'Fill-in-Blank (FIB)': 'detailed-question-types/fill-in-blanks.md'
      - 'Matching (MAT)': 'detailed-question-types/matching.md'
      - 'Ordering (ORD)': 'detailed-question-types/ordering.md'
  -  Additional Information:
      - additional-info/media-links.md
      - additional-info/sections.md
      - additional-info/points.md
      - additional-info/titles-short-descriptions.md
      - 'Using an Answer Key': 'additional-info/end-answer-key.md' 
      - 'Randomizing Answers': 'additional-info/answer-randomization.md'
      - 'Ordered List Details': 'additional-info/ordered-list-details.md'
      - additional-info/migrating-from-respondus.md
