apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=qcon-guide}

resources:
- ../../base

# Resource names in a shared namespace must be unique
#
namePrefix: qcon-guide-

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: qcon-guide
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/qcon/qcon-guide}
  newTag: ${IMAGE_TAG:=stable}

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress


# # Create a .dockerconfig.json. Then uncomment this section for local cluster development.
# #
# - target:
#     kind: Deployment
#   patch: |-
#     - op: add
#       path: /spec/template/spec/imagePullSecrets
#       value: [name: gitlab-registry-credentials]

# secretGenerator:
# - name: gitlab-registry-credentials
#   type: kubernetes.io/dockerconfigjson
#   files:
#     - .dockerconfigjson=secrets/.dockerconfig.json
