apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /nginx
  name: deployment
  labels:
    app: nginx
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|nginx'
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.24-alpine
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - emptyDir: {}
          name: tmp
