apiVersion: v1
kind: Service
metadata: # kpt-merge: /nginx
  name: service
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|nginx'
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
